src/PizzaDelivery.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace PizzaDelivery.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/PizzaDelivery.Web/Controllers/PedidosController.cs
using Microsoft.AspNetCore.Mvc;
using PizzaDelivery.Core.Models;
using PizzaDelivery.Services.Pedidos.Interfaces;

namespace PizzaDelivery.Web.Controllers
{
    [Route("pedidos")]
    public class PedidosController : Controller
    {
        private readonly IPedidoService _pedidoService;

        public PedidosController(IPedidoService pedidoService)
        {
            _pedidoService = pedidoService;
        }

        public async Task<IActionResult> Index()
        {
            return await Task.Run(() => View());
        }

        [Route("criar")]
        public async Task<IActionResult> Create()
        {
            return await Task.Run(() => View());
        }

        [Route("criarpedido")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PedidoModel pedidoModel)
        {
            if (ModelState.IsValid)
            {
                await _pedidoService.CriarPedidoAsync(pedidoModel);

                return RedirectToAction(nameof(List));
            }

            return View(pedidoModel);
        }

        [Route("listar")]
        public async Task<IActionResult> List(int statusPedido)
        {
            var listaPedidos = await _pedidoService.ObterPedidosAsync(statusPedido);

            return View(listaPedidos);
        }

        [Route("editar/{pedidoId}")]
        public async Task<IActionResult> Edit(int pedidoId)
        {
            var pedido = await _pedidoService.ObterPedidoAsync(pedidoId);

            return View(pedido);
        }

        [Route("atualizar")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PedidoModel pedidoModel)
        {
            if (ModelState.IsValid)
            {
                await _pedidoService.AtualizarPedidoAsync(pedidoModel);

                return RedirectToAction(nameof(List));
            }

            return View(pedidoModel);
        }

        [Route("excluir/{pedidoId}")]
        public async Task<IActionResult> Delete(int pedidoId)
        {
            var pedido = await _pedidoService.ObterPedidoAsync(pedidoId);

            return View(pedido);
        }

        [Route("excluirpedido/{pedidoId}")]
        public async Task<IActionResult> ConfirmDelete(int pedidoId)
        {
            await _pedidoService.ExcluirPedidoAsync(pedidoId);

            return RedirectToAction(nameof(List));
        }
    }
}

src/PizzaDelivery.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pizza Delivery - Gustavo Olivio";
}

<div class="text-center">
    <h1>AlfaPeople</h1>
    <h4>Teste Lógico</h4>
    <br />
    <br />
    <hr />
    <h4>Gustavo Olivio</h4>
    <a class="btn btn-primary" href="https://www.linkedin.com/in/gustavo-olivio" target="_blank">Linkedin</a>
    <a class="btn btn-secondary" href="https://github.com/GustavoOlivio" target="_blank">Github</a>
    <hr />

</div>

src/PizzaDelivery.Web/Views/Pedidos/Create.cshtml
@using PizzaDelivery.Core.Enums
@model PizzaDelivery.Core.Models.PedidoModel

@{
    ViewData["Title"] = "Create";
}
<h1>Incluir Pedido</h1>

<hr />
<div class="row">
    <div class="col-md-8 col-lg-4">
        <form asp-action="CriarPedido">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <partial name="_Form"></partial>

            <div class="form-group">
                <input type="submit" value="Incluir Pedido" class="btn btn-primary" />
                <a class="btn btn-danger" asp-action="Listar">Voltar à Lista</a>
            </div>
        </form>
    </div>
</div>

src/PizzaDelivery.Web/Views/Pedidos/Delete.cshtml
@model PizzaDelivery.Core.Models.PedidoModel

@{
    ViewData["Title"] = "Excluir Pedido";
}

<h3>Deseja realmente excluir o Pedido?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomeCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomeCliente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EMail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EMail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pedido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pedido)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>

    <form asp-action="ExcluirPedido">
        @Html.ActionLink("Excluir", "ExcluirPedido", new { @Model.Id }, new { @class = "btn btn-danger"}) |
        <a class="btn btn-warning" asp-action="Listar">Voltar à Lista</a>
    </form>
</div>

src/PizzaDelivery.Web/Views/Pedidos/Edit.cshtml
@using PizzaDelivery.Core.Enums
@model PizzaDelivery.Core.Models.PedidoModel

@{
    ViewData["Title"] = "Atualizar Pedido";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-8 col-lg-4">
        <form asp-action="Atualizar">

            @Html.HiddenFor(model => model.Id)
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            
            <partial name="_Form"></partial>

            <br />
            <div class="form-group">
                <input type="submit" value="Atualizar Pedido" class="btn btn-primary" />
                <a class="btn btn-warning" asp-action="Listar">Voltar à Lista</a>
            </div>
        </form>
    </div>
</div>

src/PizzaDelivery.Web/Views/Pedidos/List.cshtml
@model IEnumerable<PizzaDelivery.Core.Models.PedidoModel>

@{
    ViewData["Title"] = "Listagem de Pedidos";
}

<h1>@ViewData["Title"]</h1>
<hr />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomeCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EMail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pedido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EMail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pedido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { item.Id }, new { @class = "btn btn-warning"}) |
                    @Html.ActionLink("Excluir", "Excluir", new { item.Id }, new { @class = "btn btn-danger"})
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <p>
        <a class="btn btn-primary" asp-action="Criar">Incluir Novo Pedido</a>
    </p>
</div>
<br />

src/PizzaDelivery.Web/Views/Pedidos/_Form.cshtml
@using PizzaDelivery.Core.Enums
@model PizzaDelivery.Core.Models.PedidoModel

<div class="form-group">
    <label asp-for="NomeCliente" class="control-label"></label>
    <input asp-for="NomeCliente" class="form-control" />
    <span asp-validation-for="NomeCliente" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="EMail" class="control-label"></label>
    <input asp-for="EMail" class="form-control" />
    <span asp-validation-for="EMail" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Pedido" class="control-label"></label>
    <textarea asp-for="Pedido" class="form-control"></textarea>
    <span asp-validation-for="Pedido" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Valor" class="control-label"></label>
    <input asp-for="Valor" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Status" class="control-label"></label>
    <select asp-for="Status" class="form-control" asp-items="@Html.GetEnumSelectList<StatusPedido>()"></select>
</div>
<br />

src/PizzaDelivery.Web/Views/Shared/_Layout.cshtml
<html>
<head>
    <title>@ViewData["Title"] - Pizza Delivery</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site_bundle.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pizza Delivery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapser" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>:
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Listar">Listar Pedidos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Criar">Incluir Pedido</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-body">
        @RenderBody()
    </div>>

    <footer class="border-top blockquote-footer text-muted">
        <div class="container">PizzaDelivery - Gustavo Olivio - AlfaPeople - 2022</div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*<script src="~/js/site_bundle.min.js" asp-append-version="true"></script>*@

    <link rel="stylesheet" href="~/js/site_bundle.min.js?ver=1.332" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>